language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1
  - nightly

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Photosynthesis.jl.git"));'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Microclimate.jl.git"));'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
