language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1
  - nightly

notifications:
  email: false

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Photosynthesis.jl.git"));'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Microclimate.jl.git"));'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

codecov: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Photosynthesis.jl.git"));'
        - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/Microclimate.jl.git"));'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

codecov: true
